---
title: "Call Center Report"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bg: "#FFFFFF"
      fg: "#FDF7F7" 
      primary: "#F5E3C2"
      navbar-bg: "#554089"
      base_font:
        google: "Prompt"
      code_font:
        google: "JetBrains Mono"
    orientation: columns
    vertical_layout: fill

---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(highcharter)
library(bslib)
library(thematic)
```

```{r data, include=FALSE}
#Load data set
calls<-read_csv("Data/Call Center.csv")

#Wrangling
#calls per center
callsPerCenter<-calls%>%
  group_by(call_center)%>%
  tally()%>%
  arrange(-n)

#Reasons
callsReason<-calls%>%
  group_by(reason)%>%
  tally()%>%
  arrange(-n)

#Response
callsResponse<-calls%>%
  group_by(response_time)%>%
  tally()%>%
  arrange(-n)

#Sentiment
callsSentiment<-calls%>%
  group_by(sentiment)%>%
  tally()%>%
  arrange(-n)


#Canal
callsChannel<-calls%>%
  group_by(channel)%>%
  tally()%>%
  arrange(-n)

#Day
callsDay<-calls%>%
  group_by(call_timestamp)%>%
  tally()

#Average minutes
callsAverage<-calls%>%
  group_by(call_timestamp)%>%
  mutate(totalDay = sum(`call duration in minutes`))%>%
  mutate(averageTime = round(mean(`call duration in minutes`), digits = 2))

trendAverage<-callsAverage%>%
  group_by(call_timestamp, averageTime)%>%
  tally()%>%
  rename(callsTotalDay = n)
```


Column {data-width=400}
-----------------------------------------------------------------------

### Calls by call center

```{r}
callsPerCenter %>%
  hchart(type = "bar",
         hcaes(x = call_center, y = n, color = c(
        "#554089", 
        "#4E7CBF", 
        "#4BBEC5", 
        "#FCBE78"
      )),
         name = "Calls") %>%
  hc_yAxis(
    title = list(text = ""),
    style = list(
      fontFamily = "Roboto",
      fontSize = "12px",
      color = "#666666"
    )
  ) %>%
  hc_xAxis(title = list(text = ""), labels = list(
    style = list(
      fontFamily = "Roboto",
      fontSize = "12px",
      color = "#333333"
    )
  )) %>%  hc_legend(enabled = FALSE)

```

### Response

```{r}
callsResponse%>%
  hchart(type = "bar",
         hcaes(x = response_time, y = n, color = c(
        "#554089", 
        "#4E7CBF", 
        "#4BBEC5"
      )),
         name = "Calls")%>%
  hc_yAxis(title = list(text = ""),
           style = list(
             fontFamily = "Roboto",
             fontSize = "12px",
             color = "#666666"
           )
  ) %>%
  hc_xAxis(title = list(text = ""), labels = list(
    style = list(
      fontFamily = "Roboto",
      fontSize = "12px",
      color = "#333333"
    ) 
  ))%>%  hc_legend(enabled = FALSE)

```


Column {data-width=400}
-----------------------------------------------------------------------

### Sentiment

```{r}
callsSentiment%>%
  hchart(type = "bar",
         hcaes(x = sentiment, y = n, color = c(
        "#554089", 
        "#4E7CBF", 
        "#388F94", 
        "#4BBEC5",
        "#FCBE78"
      )),
         name = "Answers")%>%
  hc_yAxis(title = list(text = ""),
             style = list(
               fontFamily = "Roboto",
               fontSize = "12px",
               color = "#666666"
             )
           ) %>%
  hc_xAxis(title = list(text = ""), labels = list(
    style = list(
      fontFamily = "Roboto",
      fontSize = "12px",
      color = "#333333"
    ) 
  ))%>%  hc_legend(enabled = FALSE)
```

### Reasons

```{r}
callsReason%>%
  hchart(type = "bar",
         hcaes(x = reason, y = n, color = c(
        "#554089", 
        "#4E7CBF", 
        "#388F94"
      )),
         name = "Answers")%>%
  hc_yAxis(title = list(text = ""),
             style = list(
               fontFamily = "Roboto",
               fontSize = "12px",
               color = "#666666"
             )
           ) %>%
  hc_xAxis(title = list(text = ""), labels = list(
    style = list(
      fontFamily = "Roboto",
      fontSize = "12px",
      color = "#333333"
    ) 
  ))%>%  hc_legend(enabled = FALSE)
```

### Channel

```{r}
callsChannel%>%
  hchart(type = "bar",
         hcaes(x = channel, y = n, color = c(
        "#554089", 
        "#4E7CBF", 
        "#388F94", 
        "#4BBEC5"
      )),
         name = "Calls")%>%
  hc_yAxis(title = list(text = ""),
             style = list(
               fontFamily = "Roboto",
               fontSize = "12px",
               color = "#666666"
             )
           ) %>%
  hc_xAxis(title = list(text = ""), labels = list(
    style = list(
      fontFamily = "Roboto",
      fontSize = "12px",
      color = "#333333"
    ) 
  ))%>%  hc_legend(enabled = FALSE)
```

Column {data-width=400}
-----------------------------------------------------------------------

### Calls received

```{r}
callsDay%>%
  hchart(type = "line",
         hcaes(x = call_timestamp, y = n),
         name = "Calls",
         color = "#4E7CBF")%>%
  hc_yAxis(title = list(text = ""),
             style = list(
               fontFamily = "Roboto",
               fontSize = "12px",
               color = "#666666"
             )
           ) %>%
  hc_xAxis(title = list(text = ""), labels = list(
    style = list(
      fontFamily = "Roboto",
      fontSize = "12px",
      color = "#333333"
    ) 
  ))%>%  hc_legend(enabled = FALSE)
```

### Average call duration

```{r}
trendAverage%>%
  hchart(type = "line",
         hcaes(x = call_timestamp, y = averageTime),
         name = "Average",
         color = "#388F94")%>%
  hc_yAxis(title = list(text = ""),
             style = list(
               fontFamily = "Roboto",
               fontSize = "12px",
               color = "#666666"
             )
           ) %>%
  hc_xAxis(title = list(text = ""), labels = list(
    style = list(
      fontFamily = "Roboto",
      fontSize = "12px",
      color = "#333333"
    ) 
  ))%>%  hc_legend(enabled = FALSE)
```